apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wisecow-app-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - yourdomain.com
      secretName: wisecow-app-tls
  rules:
    - host: vinay-tilada.bestinthebizz.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wisecow-app-service
                port:
                  number: 80
