name: CI/CD to VM

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Build and push Docker image
      - name: Build and push Docker image
        run: |
          docker build -t vinayt05/wisecow-app:latest .
          docker push vinayt05/wisecow-app:latest

      # 4. Ensure target folder exists on VM
      - name: Create target folder on VM
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VM_HOST }}
          username: azureuser
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            mkdir -p /home/azureuser/k8s

      # 5. Copy YAML manifests to VM
      - name: Copy manifests to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VM_HOST }}
          username: azureuser
          key: ${{ secrets.VM_SSH_KEY }}
          port: 22
          source: "*.yaml"
          target: "/home/azureuser/k8s/"

      # 6. Deploy manifests on VM
      - name: Deploy on VM via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VM_HOST }}
          username: azureuser
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            set -e
            # Apply manifests in correct order
            kubectl apply -f /home/azureuser/k8s/namespace.yaml || true
            kubectl apply -f /home/azureuser/k8s/ClusterIssuer.yaml || true
            kubectl apply -f /home/azureuser/k8s/service.yaml
            kubectl apply -f /home/azureuser/k8s/deployment.yaml
            kubectl apply -f /home/azureuser/k8s/ingress.yaml
