name: Deploy to AKS

on:
  push:
    branches:
      - AKS-Cluster

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up kubectl
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      # 3. Configure kubeconfig from GitHub Secrets
      - name: Configure kubeconfig
        run: |
          echo "${{ secrets.AKS_KUBECONFIG }}" | base64 --decode > kubeconfig.yaml
          export KUBECONFIG=$(pwd)/kubeconfig.yaml
          kubectl config view

      # 4. Apply Kubernetes manifests
      - name: Deploy manifests
        run: |
          export KUBECONFIG=$(pwd)/kubeconfig.yaml
          
          echo "Applying namespace..."
          kubectl apply -f namespace.yaml || true

          echo "Applying ClusterIssuer for TLS..."
          kubectl apply -f ClusterIssuer.yaml || true

          echo "Applying Deployment and Service..."
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml

          echo "Applying ingress-nginx controller..."
          kubectl apply -f ingress-nginx-controller.yaml --wait

          echo "Applying Ingress with cert-manager annotations..."
          kubectl apply -f ingress.yaml --wait

          echo "Waiting for TLS certificate to be ready..."
          kubectl wait --for=condition=Ready certificate/wisecow-tls -n wisecow --timeout=300s || true
