name: Deploy to AKS

on:
  push:
    branches:
      - AKS-Cluster

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up kubectl
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      # 3. Use kubeconfig from GitHub Secrets
      - name: Configure kubeconfig
        run: |
          echo "${{ secrets.AKS_KUBECONFIG }}" > kubeconfig.yaml
          export KUBECONFIG=$(pwd)/kubeconfig.yaml

      # 4. Apply manifests
      - name: Deploy manifests
        run: |
          kubectl apply -f namespace.yaml
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
          kubectl apply -f ingress-nginx-controller.yaml --wait
          kubectl apply -f ingress.yaml --wait
          kubectl wait --for=condition=Ready certificate/wisecow-tls -n wisecow --timeout=300s
