name: CI/CD to VM

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t vinayt05/wisecow-app:latest .
          docker push vinayt05/wisecow-app:latest

      - name: Copy manifests to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VM_HOST }}
          username: azureuser
          key: ${{ secrets.VM_SSH_KEY }}
          port: 22
          source: "wisecow/*yaml"
          target: "/home/azureuser/"

      - name: Deploy on VM via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VM_HOST }}
          username: azureuser
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            set -e
            # Optional cleanup (prevents duplicate/old YAMLs)
            rm -f /home/azureuser/*.yaml

            # Re-copy files (ensures clean state)
            mkdir -p /home/azureuser/k8s
            cp /home/azureuser/*.yaml /home/azureuser/k8s/

            # Apply in correct order
            kubectl apply -f /home/azureuser/namespace.yaml || true
            kubectl apply -f /home/azureuser/ClusterIssuer.yaml || true
            kubectl apply -f /home/azureuser/service.yaml
            kubectl apply -f /home/azureuser/deployment.yaml
            kubectl apply -f /home/azureuser/ingress.yaml
