name: Deploy to AKS

on:
  push:
    branches:
      - AKS-Cluster  # Change to your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up kubectl
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      # 3. Configure kubeconfig from GitHub Secret
      - name: Configure kubeconfig
        run: |
          echo "${{ secrets.AKS_KUBECONFIG }}" | base64 --decode > kubeconfig.yaml
          export KUBECONFIG=$(pwd)/kubeconfig.yaml

      # 4. Install cert-manager CRDs
      - name: Install cert-manager CRDs
        run: |
          kubectl apply --kubeconfig=kubeconfig.yaml -f https://github.com/cert-manager/cert-manager/releases/latest/download/cert-manager.crds.yaml

      # 5. Install cert-manager
      - name: Install cert-manager
        run: |
          kubectl apply --kubeconfig=kubeconfig.yaml -f https://github.com/cert-manager/cert-manager/releases/latest/download/cert-manager.yaml

      # 6. Apply your namespace
      - name: Apply namespace
        run: |
          kubectl apply --kubeconfig=kubeconfig.yaml -f namespace.yaml || true

      # 7. Apply ClusterIssuer for TLS
      - name: Apply ClusterIssuer
        run: |
          kubectl apply --kubeconfig=kubeconfig.yaml -f ClusterIssuer.yaml || true

      # 8. Apply Deployment and Service
      - name: Apply Deployment and Service
        run: |
          kubectl apply --kubeconfig=kubeconfig.yaml -f deployment.yaml
          kubectl apply --kubeconfig=kubeconfig.yaml -f service.yaml

      # 9. Apply ingress-nginx controller
      - name: Apply ingress-nginx controller
        run: |
          kubectl apply --kubeconfig=kubeconfig.yaml -f ingress-nginx-controller.yaml --wait

      # 10. Apply Ingress with cert-manager TLS
      - name: Apply Ingress
        run: |
          kubectl apply --kubeconfig=kubeconfig.yaml -f ingress.yaml --wait

      # 11. Wait for TLS certificate
      - name: Wait for TLS certificate
        run: |
          kubectl wait --kubeconfig=kubeconfig.yaml --for=condition=Ready certificate/wisecow-tls -n wisecow --timeout=300s || true
