name: Deploy to AKS with TLS

on:
  push:
    branches:
      - AKS-Cluster

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up kubectl
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      # 3. Configure kubeconfig from secret
      - name: Configure kubeconfig
        run: |
          echo "${{ secrets.AKS_KUBECONFIG }}" | base64 --decode > kubeconfig.yaml
          export KUBECONFIG=$(pwd)/kubeconfig.yaml

      # 4. Create necessary namespaces
      - name: Create namespaces
        run: |
          kubectl apply -f namespace.yaml || true
          kubectl create namespace ingress-nginx || true

      # 5. Install cert-manager CRDs and cert-manager
      - name: Install cert-manager
        run: |
          kubectl apply -f https://github.com/cert-manager/cert-manager/releases/latest/download/cert-manager.crds.yaml
          kubectl apply -f https://github.com/cert-manager/cert-manager/releases/latest/download/cert-manager.yaml
          kubectl wait --for=condition=available --timeout=300s deployment/cert-manager -n cert-manager
          kubectl wait --for=condition=available --timeout=300s deployment/cert-manager-webhook -n cert-manager
          kubectl wait --for=condition=available --timeout=300s deployment/cert-manager-cainjector -n cert-manager

      # 6. Apply ClusterIssuer for TLS
      - name: Apply ClusterIssuer
        run: |
          kubectl apply -f ClusterIssuer.yaml || true

      # 7. Deploy app: Deployment and Service
      - name: Deploy app resources
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml

      # 8. Deploy ingress-nginx controller
      - name: Deploy ingress-nginx controller
        run: |
          kubectl apply -f ingress-nginx-controller.yaml --wait

      # 9. Apply Ingress with cert-manager TLS annotations
      - name: Apply Ingress
        run: |
          kubectl apply -f ingress.yaml --wait

      # 10. Wait for TLS certificate to be ready
      - name: Wait for TLS
        run: |
          kubectl wait --for=condition=Ready certificate/wisecow-tls -n wisecow --timeout=300s || true
